/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#f0f7ff',
          100: '#e0effe',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          900: '#1e3a8a',
        },
        "surface-container-highest": "#353534",
        "on-secondary": "#313030",
        "inverse-primary": "#006875",
        "surface-container-low": "#1c1b1b",
        "on-tertiary-container": "#3a5e6a",
        "error": "#ffb4ab",
        "tertiary-fixed": "#c3e8f7",
        "on-tertiary-fixed-variant": "#274c57",
        "surface-variant": "#353534",
        "primary-fixed": "#9cf0ff",
        "on-secondary-fixed-variant": "#474746",
        "surface-container": "#201f1f",
        "secondary-fixed": "#e5e2e1",
        "secondary-fixed-dim": "#c8c6c5",
        "on-error": "#690005",
        "secondary": "#c8c6c5",
        "on-tertiary": "#0d3540",
        "surface-container-lowest": "#0e0e0e",
        "background": "#131313",
        "on-secondary-fixed": "#1c1b1b",
        "on-primary-fixed-variant": "#004f58",
        "on-primary-fixed": "#001f24",
        "on-primary-container": "#00626e",
        "on-background": "#e5e2e1",
        "outline-variant": "#3b494c",
        "on-surface-variant": "#bac9cc",
        "tertiary-container": "#b1d6e4",
        "primary-fixed-dim": "#00daf3",
        "on-primary": "#00363d",
        "surface-container-high": "#2a2a2a",
        "primary-container": "#00e5ff",
        "surface-tint": "#00daf3",
        "primary": "#c3f5ff",
        "inverse-surface": "#e5e2e1",
        "tertiary": "#d0f2ff",
        "tertiary-fixed-dim": "#a7ccda",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#313030",
        "secondary-container": "#474746",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#001f28",
        "outline": "#849396",
        "on-surface": "#e5e2e1",
        "surface-bright": "#3a3939"
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
